# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_turtlerabbit_ssl_agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%messages_turtlerabbit_ssl_agent.proto\x12\x0fTurtleRabbitSSL\"D\n\x11RobotAgentCommand\x12\n\n\x02id\x18\x01 \x02(\r\x12\n\n\x02vx\x18\x02 \x02(\x02\x12\n\n\x02vy\x18\x03 \x02(\x02\x12\x0b\n\x03tfd\x18\x04 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_turtlerabbit_ssl_agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROBOTAGENTCOMMAND']._serialized_start=58
  _globals['_ROBOTAGENTCOMMAND']._serialized_end=126
# @@protoc_insertion_point(module_scope)
